[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
name = "diary_core"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "1.59.0"
vault-core = "0.1.1"
zeroize = "1.5.7"
